export enum defaultAvatarEnum {
  backgroundColor = "c0aede",
  earrings = "variant03",
  earringsProbability = 0,
  eyebrows = "variant10",
  eyes = "variant17",
  features = "birthmark",
  featuresProbability = 0,
  flip = 1,
  glasses = "variant04",
  glassesProbability = 0,
  hair = "short07",
  hairColor = "6a4e35",
  hairProbability = 100,
  mouth = "variant10",
  seed = "ExpressoTS",
  skinColor = "ecad80",
}
